/*
 * qmi-band-class.h
 *
 *  Created on: 06.06.2012
 *      Author: roland
 */

#ifndef _LIBQMI_GLIB_QMI_BAND_CLASS_H_
#define _LIBQMI_GLIB_QMI_BAND_CLASS_H_

#include <glib.h>

typedef enum {
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_1		=	120,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_2,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_3,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_4,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_5,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_6,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_7,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_8,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_9,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_10,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_11,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_12,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_13,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_14,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_17,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_33,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_34,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_35,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_36,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_37,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_38,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_39,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_40,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_18,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_19,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_20,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_21,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_22,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_23,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_24,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_25,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_41,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_42,
	NAS_ACTIVE_BAND_E_UTRA_OPERATING_BAND_43

}QmiBandEnum;

const gchar* qmi_band_enum_get_string(QmiBandEnum val);



#endif /* _LIBQMI_GLIB_QMI_BAND_CLASS_H_ */
